# Node.js with Vue
# Build a Node.js project that uses Vue.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

variables:
  # Agent VM image name
  vmImageName: 'ubuntu-latest'

  # Working Directory
  workingDirectory: '$(System.DefaultWorkingDirectory)/'

stages:
  - stage: Build
    displayName: Build stage

    jobs:
    - job: imageworx_build
      displayName: ImageWorx Client Build
      pool:
        vmImage: $(vmImageName)
      steps:
      - task: NodeTool@0
        inputs:
          versionSpec: '10.x'
        displayName: 'Install Node.js'

      - script: |
          npm install
          npm run build
        displayName: 'npm install and build'

      - task: ArchiveFiles@2
        inputs:
          rootFolderOrFile: '$(workingDirectory)/dist'
          includeRootFolder: false
          archiveFile: $(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip

      - task: PublishBuildArtifacts@1
        inputs:
          PathtoPublish: $(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip

  - stage: Deploy
    displayName: Deploy stage
    dependsOn: Build
    condition: succeeded()

    jobs:
    - deployment: Deploy
      displayName: Deploy
      environment: 'development'
      pool:
        vmImage: $(vmImageName)

      strategy:
        runOnce:
          deploy:

            steps:
            - task: AzureWebApp@1
              displayName: 'Azure web app deploy'
              inputs:
                azureSubscription: '$(azureSubscription)'
                appType: 'webAppLinux'
                appName: '$(appName)'
                package: '$(Pipeline.Workspace)/drop/$(Build.BuildId).zip'
                runtimeStack: 'NODE|10-lts'
